### ISSUE TITLE
Can't get the LaunchAgent to work

### ISSUE THREAD

**Issue by xXBeekeyXx** [pushrax/osxmpdkeys#10]
LaunchAgent string does not correspond to Program location (output of 'which mpdkeys')

I have saved the plist-file in the correct location, but mpdkeys isn't loaded at login. I tried manually loading and starting via launchctl - still not working.

**Comment by pushrax** [comment]
It’s possible that in your python environment, pip installed the executable somewhere else. Does it work if you update the path to the location reported by `which`?

**Comment by xXBeekeyXx** [comment]
Hello, thank you so much for the reply. I could have sworn that I already tried that but well, it works now :)) Thanks for your package, I really appreciate it!
