### ISSUE TITLE
Media keys are not detected if playback is stopped

### ISSUE THREAD

**Issue by shrx** [pushrax/osxmpdkeys#2]
`Previous`, `Next`, `Play/Pause` keys only work if the playback is "playing" or "paused". They don't work if the playback is "stopped". Is it possible to use the media keys even if the playback is stopped?

**Comment by pushrax** [comment]
Implemented in e0553aba0a0d3a865a9c55700421b865bd6fc32a, osxmpdkeys 0.0.4. You can update with `pip install -U osxmpdkeys`

**Comment by shrx** [comment]
Thanks for the quick implementation.
