### ISSUE TITLE
Allow remapping of rewind/fastforward to previous/next track

### ISSUE THREAD

**Issue by andrewrabert** [pushrax/osxmpdkeys#7]
An external keyboard of mine is configured with traditional Windows/Linux media control keys. This means that the previous and next track keys are mapped to rewind and fastforward on macOS.

osxmpdkeys should allow for using these to change tracks in MPD. I've confirmed this can be achieved by modifiying 'next_track' and 'prev_track' in `osxmmkeys.tap.KEY_CODES` to the appropriate keycodes. This should be configurable with a CLI option.

```
    KEY_CODES = {
        16: 'play_pause',
        17: 'next_track',
        18: 'prev_track',
        7: 'mute',
        1: 'volume_down',
        0: 'volume_up',
        3: 'backlight_down',
        2: 'backlight_up',
        22: 'kb_backlight_down',
        21: 'kb_backlight_up',
    }
```

**Comment by giann** [comment]
That works for me ! Thanks !

**Comment by pushrax** [comment]
It's unlikely I'll get around to implementing this as an option soon. Anyone who feels like contributing a patch is welcome to do so.

**Comment by andrewrabert** [comment]
@pushrax Didn't make it configurable, but it works. https://github.com/pushrax/osxmmkeys/pull/1

**Comment by pushrax** [comment]
Merged and updated dependencies.
